name: reqnotes # you probably want to 'snapcraft register <name>'
version: '1.0.1' # just for humans, typically '1.2+git' or '1.3.2'
grade: devel # must be 'stable' to release into candidate/stable channels
summary: Get the current time in various cities around the world # 79 char long summary
description: |
  Whatime is able to get you the current time in several different cities
  around the world.

base: core22 # the base snap is the execution environment for this snap

confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  reqnotes:
    # See 'snapcraft plugins'
    plugin: dotnet
    dotnet-build-configuration: Release
    dotnet-self-contained-runtime-identifier: linux-x64
    source: .
    build-packages:
      - dotnet-sdk-6.0
    stage-packages:
      - libicu70
      - libx11-6
      - libice6
      - libsm6
      - libfontconfig1

apps:
  reqnotes:
    command: ReqNotes